name: Android

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 8
          distribution: adopt
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug